frontend/controllers/EventController.php
<?php

namespace frontend\controllers;

use common\models\Event;
use common\models\Sector;
use common\models\Ticket;
use frontend\models\EventSearch;
use frontend\models\form\TicketForm;
use frontend\widgets\Growl;
use Yii;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Event controller
 */
class EventController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionSearch($q = null)
    {
        if (!isset($q)) {
            $q = Yii::$app->request->post('q');
        }
        if (isset($q)) {
            $query = Event::find()->andWhere(['or',
                ['like', 'description', $q],
                ['like', 'title', $q],
                ['like', 'location', $q],
            ])->limit(200);
            $searchModel = new EventSearch();
            $searchModel->title = $q;
        } else {
            $searchModel = new EventSearch();
            if ($searchModel->load(Yii::$app->request->post())) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($searchModel);
                } else {
                    $query = $searchModel->generateQuery(Yii::$app->request->post());
                }
            } else {
                throw new BadRequestHttpException();
            }
        }
        $events = $query->all();
        return $this->render('search-results', [
            'query' => $q,
            'events' => $events,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        Url::remember();
        $model = $this->findModel($id);
        $sectors = $model->sectors;

        $categoryEvents = Event::find()->category($model->idCategory)->andWhere(['!=', 'Event.idEvent', $model->idEvent])->limit(4)->all();
        return $this->render('view', ['event' => $model, 'sectors' => $sectors, 'categoryEvents' => $categoryEvents]);
    }

    public function actionAddToCart()
    {
        $model = new TicketForm();
        if ($model->load($_POST)) {
            $sector = $this->findSectorModel($model->idSector);
            $event = $sector->event;
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->create()) {
                Growl::add(Growl::SUCCESS,
                    Yii::t('app', 'Sono stati aggiunti al carrello <b>{quantity}</b> biglietti per il settore <b>{sector}</b> dell\'evento <b>{event}</b>', [
                        'quantity' => $model->quantity,
                        'sector' => $sector->description,
                        'event' => $event->title,
                    ]),
                    Yii::t('app', 'Biglietto/i aggiunti al carrello.'),
                    'fa fa-cart-plus'
                );
                return $this->goBack();
            }
        }
        throw new BadRequestHttpException();
    }

    public function actionCart()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello()->orderBy('Event.idEvent, Sector.idSector');
        $tickets = $query->all();
        if (count($tickets) == 0) {
            return $this->redirect(['site/index']);
        }
        $total = $query->sum('Sector.price');
        return $this->render('cart', ['tickets' => $tickets, 'totalCount' => $total]);
    }

    public function actionCartDelete($id)
    {
        $ticket = $this->findTicketModel($id);
        $sector = $ticket->sector;
        $event = $sector->event;
        if ($ticket->idUser != Yii::$app->user->getId()) throw new ForbiddenHttpException();
        if ($ticket->delete()) {
            Growl::add(Growl::WARNING, Yii::t('app', 'Biglietto <b>{ticket}</b> per <b>{event}</b> - <b>{sector}</b> rimosso dal carrello', [
                'ticket' => $ticket->info,
                'event' => $event->title,
                'sector' => $sector->description,
            ]));
        }
        return $this->goBack();
    }

    public function actionPurchaseCart()
    {
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello();
        $tickets = $query->all();
        foreach ($tickets as $ticket) {
            $ticket->purchase();
        }
        Growl::add(Growl::SUCCESS,
            Yii::t('app', 'Troverà i suoi biglietti nella sua area personale.'),
            Yii::T('app', 'Grazie per l\'acquisto!'),
            'fa fa-check'
        );
        return $this->redirect(['personal-area/tickets']);
    }

    /**
     * @param $id
     * @return Event|null
     * @throws NotFoundHttpException
     */
    public function findModel($id)
    {
        $model = Event::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Sector|null
     * @throws NotFoundHttpException
     */
    public function findSectorModel($id)
    {
        $model = Sector::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Ticket|null
     * @throws NotFoundHttpException
     */
    public function findTicketModel($id)
    {
        $model = Ticket::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }
}

frontend/controllers/PersonalAreaController.php
<?php

namespace frontend\controllers;

use common\models\Event;
use common\models\Sector;
use common\models\Ticket;
use frontend\models\form\EventForm;
use frontend\widgets\Growl;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Personal Area Controller
 */
class PersonalAreaController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionDetail()
    {
        Url::remember();
        $model = Yii::$app->user->identity;
        return $this->renderView($model, 'detail', ['model' => $model]);
    }

    public function renderView($model, $view, $params = [])
    {
        return $this->render('view', ['model' => $model,
            'content' => $this->renderPartial($view, $params)
        ]);
    }

    public function actionEventCreate()
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $model = new EventForm();
        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->create()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento creato correttamente'));
                return $this->redirect(['personal-area/event-detail', 'id' => $model->idEvent]);
            }
        }
        return $this->renderView($user, 'event-create', ['model' => $model]);
    }

    public function actionDashboard()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $query = Event::find()->orderBy('Event.dateTime');
        if (!$user->isAdmin()) {
            $query->createdBy($user->id);
        }
        $events = $query->all();
        $idEvents = array_values(ArrayHelper::map($events, 'idEvent', 'idEvent'));
        $countSoldTickets = Ticket::find()->joinWith('sector')
            ->sold()->andWhere(['Sector.idEvent' => $idEvents])->count();
        $totalSoldTickets = Ticket::find()->joinWith('sector')
            ->sold()->andWhere(['Sector.idEvent' => $idEvents])->sum('Sector.price');
        $countUnsoldTickets = Sector::find()->andWhere(['Sector.idEvent' => $idEvents])->sum('maxTickets') - $countSoldTickets;
        return $this->renderView($user, 'dashboard', [
            'events' => $events,
            'countSoldTickets' => $countSoldTickets,
            'totalSoldTickets' => $totalSoldTickets,
            'countUnsoldTickets' => $countUnsoldTickets,
        ]);
    }

    public function actionEvents()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $query = Event::find()->orderBy('Event.dateTime');
        if (!$user->isAdmin()) {
            $query->createdBy($user->id);
        }
        $events = $query->all();

        return $this->renderView($user, 'events', ['events' => $events]);
    }

    public function actionEventDetail($id)
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        $sectors = $model->sectors;
        return $this->renderView($user, 'event-detail', [
            'model' => $model,
            'sectors' => $sectors,
        ]);
    }

    public function actionEventDelete($id)
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        if ($model->delete()) {
            Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento eliminato correttamente'));
        }
        return $this->redirect(['personal-area/events']);
    }

    public function actionEventUpdate($id)
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->save()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento modificato correttamente'));
                return $this->goBack();
            }
        }
        return $this->renderView($user, 'event-update', ['model' => $model]);
    }

    public function actionSectorCreate()
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $model = new Sector();
        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->save()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Settore creato correttamente'));
                return $this->goBack();
            }
        }
        return $this->renderView($user, 'event-create', ['model' => $model]);
    }

    public function actionSectorDelete($id)
    {
        $sector = $this->findSectorModel($id);
        $event = $sector->event;
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        if (!$user->isAdmin() && $event->idUser != $user->getId()) throw new ForbiddenHttpException();
        if ($sector->delete()) {
            Growl::add(Growl::SUCCESS, Yii::t('app', 'Settore eliminato correttamente'));
        }
        return $this->goBack();
    }

    public function actionTickets()
    {
        $user = Yii::$app->user->identity;
        $tickets = $user->getTickets()
            ->sold()
            ->joinWith(['sector', 'sector.event'])
            ->orderBy('Event.dateTime desc')
            ->all();
        return $this->render('tickets', ['tickets' => $tickets]);

    }

    /**
     * @param $id
     * @return Event|null
     * @throws NotFoundHttpException
     */
    public function findEventModel($id)
    {
        $model = Event::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Sector|null
     * @throws NotFoundHttpException
     */
    public function findSectorModel($id)
    {
        $model = Sector::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }
}

frontend/views/personal-area/dashboard.php
<?php

use common\models\Ticket;
use dosamigos\chartjs\ChartJs;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\View;
use yii2fullcalendar\yii2fullcalendar;

/**
 * @var $this View
 * @var $tickets Ticket[]
 * @var $countSoldTickets int
 * @var $totalSoldTickets int
 * @var $countUnsoldTickets int
 */

$this->title = Yii::t('app', 'Dashboard manager');

$calendarEvents = [];
foreach ($events as $event) {
    $calendarEvent = new \yii2fullcalendar\models\Event();
    $calendarEvent->id = $event->idEvent;
    $calendarEvent->title = $event->title;
    $calendarEvent->url = Url::to(['personal-area/event-detail', 'id' => $event->idEvent]);
    $calendarEvent->start = date('Y-m-d', $event->dateTime);
    $calendarEvent->end = date('Y-m-d', $event->dateTime + 1);
    $calendarEvent->allDay = true;
    if (isset($event->category)) {
        $calendarEvent->color = $event->category->color;
    }
    $calendarEvents[$event->idEvent] = $calendarEvent;
}
?>
<h1 class="text-center" style="margin-top: 2%;"><?= $this->title ?></h1>

        <div class="row dashboard-row">
            <div class="col-md-4">
                <table class="table table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th colspan="2" scope="col"><h3>Informazioni Generali</h3></th>
                    </tr>
                    </thead>
                <tr>
                    <td>Bigletti totali venduti</td>
                    <td><?= Yii::$app->formatter->asInteger($countSoldTickets) ?></td>
                </tr>
                <tr>
                    <td>Importo totale vendite</td>
                    <td><?= Yii::$app->formatter->asCurrency($totalSoldTickets); ?></td>
                </tr>
                <tr>
                    <td>Biglietti da vendere</td>
                    <td><?= Yii::$app->formatter->asInteger($countUnsoldTickets) ?></td>
                </tr>
                </table>
            </div>
            <div class="col-md-8 charts bg-light rounded shadow">
                <?php $firstEvents = array_splice($events, 0, 4); ?>
                <?= ChartJs::widget([
                    'type' => 'bar',
                    'options' => [
                        'height' => 200,
                        'width' => 400
                    ],
                    'data' => [
                        'labels' => ArrayHelper::getColumn($firstEvents, 'title'),
                        'datasets' => [
                            [
                                'label' => 'Percentuale di vendita',
                                'data' => ArrayHelper::getColumn($firstEvents, 'percentageSoldTickets'),
                                'backgroundColor' => "rgb(31, 40, 51)",
                            ],
                        ],
                    ],

                    'clientOptions' => [
                        'scales' => [
                            'yAxes' => [
                                'stacked' => true,
                                'ticks' => [
                                    'beginAtZero' => true,
                                    'max' => 100,
                                ]
                            ],
                        ]
                    ]
                ]); ?>
                <?php
                $start = date('U', strtotime("-15 days"));
                $end = date('U');
                $dateEnd = date('U', strtotime("-1 day", $start));
                $dateStart = $start;
                $labels = [];
                $data = [];
                while ($dateEnd <= $end) {
                    $labels[] = date('d-m', $dateStart);
                    $data[] = Ticket::find()->sold()->andWhere(['between', 'dateTime', $dateStart, $dateEnd])->count();
                    $dateStart = $dateEnd;
                    $dateEnd = date('U', strtotime("+1 day", $dateEnd));
                }
                ?>
            </div>
        </div>
        <div class="row dashboard-row">
            <div class="col-md-4">
                <div style="height: 70vh">
                    <?= yii2fullcalendar::widget([
                        'id' => 'calendar',
                        'defaultView' => 'listMonth',
                        'events' => array_values($calendarEvents),
                        'themeSystem' => 'bootstrap4',
                        'clientOptions' => [
                            'header' => [
                                'left' => 'today prev,next',
                                'center' => '',
                                'right' => 'title',
                            ],
                            'height' => 'parent',
                        ],
                    ]); ?>
                </div>
            </div>
            <div class="col-md-8 charts bg-light rounded shadow">
                <?= ChartJs::widget([
                    'type' => 'line',
                    'options' => [
                        'height' => 200,
                        'width' => 400
                    ],
                    'data' => [
                        'labels' => $labels,
                        'datasets' => [
                            [
                                'label' => 'Andamento vendite giornaliere',
                                'data' => $data,
                                'backgroundColor' => "rgb(31, 40, 51)",
                            ],
                        ],
                    ],

                    'clientOptions' => [
                        'scales' => [
                            'yAxes' => [
                                'stacked' => true,
                                'ticks' => [
                                    'beginAtZero' => true,
                                    'max' => 100,
                                ]
                            ],
                        ]
                    ]
                ]); ?>
            </div>
        </div>

frontend/views/personal-area/detail.php
<?php

use common\models\User;
use yii\web\View;

/**
 * @var $this View
 * @var $model User
 */

$this->title = Yii::t('app', 'Dettaglio account');
?>
<div class="container">
    <h1 class="text-center mt-3"><?= $this->title ?></h1><br>
    Email: <b><?= $model->email ?></b><br>
    Username: <?= $model->username ?><br>
    Nome: <?= $model->name ?><br>
    Cognome: <?= $model->surname ?><br>
</div>

frontend/views/personal-area/event-create.php
<?php

use common\models\Category;
use frontend\models\form\EventForm;
use kartik\datecontrol\DateControl;
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $model EventForm
 */

$this->title = Yii::t('app', 'Nuovo evento');
$categories = Category::find()->all();
$categoriesData = ArrayHelper::map($categories, 'idCategory', 'description');
?>

    <h1 class="new-event text-center mt-3"><?= $this->title ?></h1><br>

<?php
$form = yii\widgets\ActiveForm::begin([
    'action' => Url::to(['personal-area/event-create']),
    'options' => ['enctype' => 'multipart/form-data']
]);
?>
    <div class="container"> <!-- QUI PUOI SCRIVERE HTML COME VUOI -->
        <div class="col-lg-5 left-input">
            <?= $form->field($model, 'title') ?>
            <?= $form->field($model, 'description')->textarea() ?>
            <?= $form->field($model, 'idCategory')->widget(Select2::class, [
                'data' => $categoriesData
            ]) ?>
            <?= $form->field($model, 'dateTime')->widget(DateControl::class, [
                'type' => DateControl::FORMAT_DATETIME
            ]) ?>
            <?= $form->field($model, 'dateTimeSellStart')->widget(DateControl::class, [
                'type' => DateControl::FORMAT_DATETIME
            ]) ?>
            <?= $form->field($model, 'dateTimeSellEnd')->widget(DateControl::class, [
                'type' => DateControl::FORMAT_DATETIME
            ]) ?>
        </div>
        <div class="col-lg-5 right-input">
            <?= $form->field($model, 'location') ?>
            <?= $form->field($model, 'latitude') ?>
            <?= $form->field($model, 'longitude') ?>
            <?= $form->field($model, 'previewUpload')->widget(FileInput::class, [
                'pluginOptions' => [
                    'showPreview' => true,
                    'showCaption' => true,
                    'showRemove' => true,
                    'showUpload' => false
                ]
            ]); ?>
      </div>
      <div class="col-lg-5">
        <input type="submit" value="Invia" class="btn btn-create-event mt-3">
      </div>
    </div>
<?php
$form::end();

frontend/views/personal-area/event-detail.php
<?php

use common\models\Event;
use common\models\Sector;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $model Event
 * @var $sectors Sector[];
 */
$formModel = new Sector();
$formModel->idEvent = $model->idEvent;

$this->title = Yii::t('app', '{title}', ['title' => $model->title]);
?>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h1 class="text-center mt-3 mb-3"><?= $this->title ?></h1>
            <div class="text-justify"><strong>Descrizione: </strong><?= $model->description; ?><br><br><br></div>
            <strong>Luogo: </strong><?= $model->location ?><br>
            <strong>Data e ora: </strong><?= Yii::$app->formatter->asDatetime($model->dateTime); ?><br>
            <hr>
            <a class="btn btn-danger btn-delete-sector"
               href="<?= Url::to(['personal-area/event-delete', 'id' => $model->idEvent]) ?>"
               data-confirm="Sei sicuro di voler eliminare l'evento ?"
            ><span class="fa fa-trash"></span> Elimina Evento</a>
        </div>
        <div class="col-lg-6">
            <br>
            <h2>Nuovo settore</h2>
            <?php $form = ActiveForm::begin([
                'action' => Url::to(['personal-area/sector-create']),
                'enableAjaxValidation' => true,
            ]); ?>
            <?= $this->render('sector-form', [
                'model' => $formModel,
                'form' => $form,
          ]); ?>
        <?php $form::end(); ?>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-10">
        <h2 class="mt-3">Settori:</h2>
        <hr>
        <?php if (count($sectors) == 0): ?>
            Nessun settore trovato
        <?php endif; ?>
        <?php foreach ($sectors as $sector): ?>
            <h3><?= $sector->description ?></h3>
            <strong>Prezzo: </strong><?= Yii::$app->formatter->asCurrency($sector->price); ?><br>
            <strong>Posti disponibili: </strong><?= $sector->maxTickets ?><br>
            <strong>Biglietti venduti: </strong><?= $sector->getTickets()->sold()->count() ?><br>
            <strong>Colore: </strong><span class="badge" style="background-color:<?= $sector->color ?>">&nbsp;</span><br>
            <a href="<?= Url::to(['personal-area/sector-delete', 'id' => $sector->idSector]); ?>"
               class="btn btn-danger btn-delete-sector mt-3"
               data-confirm="Conferma eliminazione settore"><span class="fa fa-trash"></span> Elimina settore</a>
            <hr>
        <?php endforeach; ?>
    </div>
  </div>
</div>

frontend/views/personal-area/tickets.php
<?php

use common\models\Ticket;
use yii\helpers\Url;
use yii\web\View;
use yii2fullcalendar\yii2fullcalendar;

/**
 * @var $this View
 * @var $tickets Ticket[]
 */

$this->title = Yii::t('app', 'I miei biglietti');
if (count($tickets) > 0) {
    $date = date('Y-m-d', end($tickets)->sector->event->dateTime);
} else {
    $date = date('Y-m-d');
}
$calendarEvents = [];
foreach ($tickets as $ticket) {
    $sector = $ticket->sector;
    $event = $sector->event;
    if (!isset($calendarEvents[$event->idEvent])) {
        $calendarEvent = new \yii2fullcalendar\models\Event();
        $calendarEvent->id = $event->idEvent;
        $calendarEvent->title = $event->title;
        $calendarEvent->url = Url::to(['event/view', 'id' => $event->idEvent]);
        $calendarEvent->start = date('Y-m-d', $event->dateTime);
        $calendarEvent->end = date('Y-m-d', $event->dateTime + 1);
        $calendarEvent->allDay = true;
        if (isset($event->category)) {
            $calendarEvent->color = $event->category->color;
        }
        $calendarEvents[$event->idEvent] = $calendarEvent;
    }
}


/**
 * @var $events Event[]
 * @var $ticketEvents Ticket[]
 */
$events = [];
$ticketEvents = [];
foreach ($tickets as $ticket) {
    if (!isset($events[$ticket->sector->idEvent])) {
        $events[$ticket->sector->idEvent] = $ticket->sector->event;
        $ticketEvents[$ticket->sector->idEvent] = [];
    }
    $ticketEvents[$ticket->sector->idEvent][] = $ticket;
}
?>
<h1 class="text-center mt-3 mb-5"><?= $this->title ?></h1>

<div class="row">
  <div class="col-lg-4">
    <?php foreach ($events as $event): ?>
        <div class="shadow bg-light ml-5 mr-5 mb-4 p-2">
          <h4 class="mb-3"><b><?= $event->title ?></b></h4>
          <?= $event->location ?><b class="text-success"><br><?= Yii::$app->formatter->asDatetime($event->dateTime) ?></b>
            <?php foreach ($ticketEvents[$event->idEvent] as $ticket): ?>
              <hr>
                <?php $sector = $ticket->sector; ?>
                <b>Info biglietto</b>
                Biglietto numero: <?= $ticket->info ?><br>
                Settore: <?= $sector->description; ?><br>
                Prezzo: <?= Yii::$app->formatter->asCurrency($sector->price) ?><br><br>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
  </div>
  <div class="col-lg-7">
    <div class="calendar">
        <?= yii2fullcalendar::widget([
            'id' => 'calendar',
            'defaultView' => 'month',
            'events' => array_values($calendarEvents),
            'themeSystem' => 'bootstrap4',
            'clientOptions' => [
                'defaultDate' => $date,
                'header' => [
                    'left' => 'today prev,next',
                    'center' => 'title',
                    'right' => 'month,listYear',
                ],
                'height' => 'parent',
            ],
        ]); ?>
    </div>
  </div>
</div>

frontend/views/personal-area/view.php
<?php

use common\models\User;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $content string
 * @var $model User
 */

$action = Yii::$app->requestedAction->id;
?>
<?php if ($model->isManager()): ?>
    <div class="row flex-fill fill d-flex">
        <div class="col-lg-2 side-bar">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <span>Benvenuto <?= Yii::$app->user->identity->name ?></span>
                <div class="container side-bar-container">
                    <a class="nav-link <?= $action == 'dashboard' ? 'active' : '' ?>"
                       href="<?= Url::to(['personal-area/dashboard']) ?>"><i class="fas fa-chart-line"></i>
                        Dashboard</a>
                    <a class="nav-link <?= $action == 'events' ? 'active' : '' ?>"
                       href="<?= Url::to(['personal-area/events']) ?>"><i class="fas fa-calendar-alt"></i> Gestione
                        eventi</a>
                    <a class="nav-link <?= $action == 'event-create' ? 'active' : '' ?>"
                       href="<?= Url::to(['personal-area/event-create']) ?>"><i class="fas fa-plus"></i> Crea evento</a>
                    <a class="nav-link <?= $action == 'detail' ? 'active' : '' ?>"
                       href="<?= Url::to(['personal-area/detail']) ?>"><i class="fas fa-cog"></i> Opzioni</a>
                    <a class="nav-link" href="<?= Url::to(['site/logout']) ?>"><i class="fas fa-sign-out-alt"></i>
                        Logout</a>
                </div>
            </div>
        </div>
        <div class="col-lg-10">
            <?= $content ?>
        </div>
    </div>
<?php else: ?>
    <?= $content ?>
<?php endif; ?>