common/models/Event.php
<?php

namespace common\models;

use common\models\query\EventQuery;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "Event".
 *
 * @property int $idEvent
 * @property string $title
 * @property string|null $description
 * @property string $dateTime
 * @property string $dateTimeSellStart
 * @property string $dateTimeSellEnd
 * @property string $location
 * @property float $latitude
 * @property float $longitude
 * @property string $state
 * @property string|null $urlPreview
 * @property int|null $idUser
 * @property int|null $idCategory
 *
 * @property User $user
 * @property Category $category
 * @property Media[] $media
 * @property mixed $percentageSoldTickets
 * @property string $previewPath
 * @property int $soldTickets
 * @property int $countTickets
 * @property Sector[] $sectors
 */
class Event extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'Event';
    }

    /**
     * {@inheritdoc}
     * @return EventQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new EventQuery(get_called_class());
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'dateTime'], 'required'],
            [['dateTime', 'dateTimeSellStart', 'dateTimeSellEnd'], 'safe'],
            [['latitude', 'longitude'], 'number'],
            [['idUser', 'idCategory'], 'integer'],
            [['title', 'location', 'state', 'urlPreview'], 'string', 'max' => 50],
            [['description'], 'string'],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['idUser' => 'idUser']],
            [['idCategory'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['idCategory' => 'idCategory']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idEvent' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Titolo'),
            'description' => Yii::t('app', 'Descrizione'),
            'dateTime' => Yii::t('app', 'Data e ora'),
            'dateTimeSellStart' => Yii::t('app', 'Inizio vendita'),
            'dateTimeSellEnd' => Yii::t('app', 'Fine vendita'),
            'location' => Yii::t('app', 'Luogo'),
            'Latitude' => Yii::t('app', 'Latitudine'),
            'longitude' => Yii::t('app', 'Longitudine'),
            'state' => Yii::t('app', 'Stato'),
            'URLPreview' => Yii::t('app', 'URL Anteprima'),
            'idUser' => Yii::t('app', 'Utente'),
            'idCategory' => Yii::t('app', 'Categoria'),
        ];
    }

    public function insert($runValidation = true, $attributes = null)
    {
        $this->idUser = Yii::$app->user->id;
        return parent::insert($runValidation, $attributes);
    }

    public function getPreviewPath()
    {
        if (empty($this->urlPreview)) {
            return Yii::getAlias('@web/img/defaultPreview.jpg');
        }
        return Yii::getAlias('@web/uploads/') . $this->urlPreview;
    }

    public function getCountTickets()
    {
        $count = 0;
        $sectors = $this->sectors;
        foreach ($sectors as $sector) {
            $count += $sector->maxTickets;
        }
        return $count;
    }

    public function getSoldTickets()
    {
        $count = 0;
        $sectors = $this->sectors;
        foreach ($sectors as $sector) {
            $count += $sector->maxTickets - $sector->remainingTickets;
        }
        return $count;
    }

    public function getPercentageSoldTickets()
    {
        $soldTickets = $this->soldTickets;
        $countTickets = $this->countTickets;
        if ($countTickets > 0) {
            return ((double)$this->soldTickets) * 100 / ((double)$this->countTickets);
        }
        return 0;
    }

    /**
     * @return ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['idUser' => 'idUser']);
    }

    /**
     * @return ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['idCategory' => 'idCategory']);
    }

    /**
     * @return ActiveQuery
     */
    public function getMedia()
    {
        return $this->hasMany(Media::class, ['idEvent' => 'idEvent']);
    }

    /**
     * @return ActiveQuery
     */
    public function getSectors()
    {
        return $this->hasMany(Sector::class, ['idEvent' => 'idEvent']);
    }
}

frontend/controllers/EventController.php
<?php

namespace frontend\controllers;

use common\models\Event;
use common\models\Sector;
use common\models\Ticket;
use frontend\models\EventSearch;
use frontend\models\form\TicketForm;
use frontend\widgets\Growl;
use Yii;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Event controller
 */
class EventController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionSearch($q = null)
    {
        if (!isset($q)) {
            $q = Yii::$app->request->post('q');
        }
        if (isset($q)) {
            $query = Event::find()->andWhere(['or',
                ['like', 'description', $q],
                ['like', 'title', $q],
                ['like', 'location', $q],
            ])->limit(200);
            $searchModel = new EventSearch();
            $searchModel->title = $q;
        } else {
            $searchModel = new EventSearch();
            if ($searchModel->load(Yii::$app->request->post())) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($searchModel);
                } else {
                    $query = $searchModel->generateQuery(Yii::$app->request->post());
                }
            } else {
                throw new BadRequestHttpException();
            }
        }
        $events = $query->all();
        return $this->render('search-results', [
            'query' => $q,
            'events' => $events,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        Url::remember();
        $model = $this->findModel($id);
        $sectors = $model->sectors;

        $categoryEvents = Event::find()->category($model->idCategory)->andWhere(['!=', 'Event.idEvent', $model->idEvent])->limit(4)->all();
        return $this->render('view', ['event' => $model, 'sectors' => $sectors, 'categoryEvents' => $categoryEvents]);
    }

    public function actionAddToCart()
    {
        $model = new TicketForm();
        if ($model->load($_POST)) {
            $sector = $this->findSectorModel($model->idSector);
            $event = $sector->event;
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->create()) {
                Growl::add(Growl::SUCCESS,
                    Yii::t('app', 'Sono stati aggiunti al carrello <b>{quantity}</b> biglietti per il settore <b>{sector}</b> dell\'evento <b>{event}</b>', [
                        'quantity' => $model->quantity,
                        'sector' => $sector->description,
                        'event' => $event->title,
                    ]),
                    Yii::t('app', 'Biglietto/i aggiunti al carrello.'),
                    'fa fa-cart-plus'
                );
                return $this->goBack();
            }
        }
        throw new BadRequestHttpException();
    }

    public function actionCart()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello()->orderBy('Event.idEvent, Sector.idSector');
        $tickets = $query->all();
        if (count($tickets) == 0) {
            return $this->redirect(['site/index']);
        }
        $total = $query->sum('Sector.price');
        return $this->render('cart', ['tickets' => $tickets, 'totalCount' => $total]);
    }

    public function actionCartDelete($id)
    {
        $ticket = $this->findTicketModel($id);
        $sector = $ticket->sector;
        $event = $sector->event;
        if ($ticket->idUser != Yii::$app->user->getId()) throw new ForbiddenHttpException();
        if ($ticket->delete()) {
            Growl::add(Growl::WARNING, Yii::t('app', 'Biglietto <b>{ticket}</b> per <b>{event}</b> - <b>{sector}</b> rimosso dal carrello', [
                'ticket' => $ticket->info,
                'event' => $event->title,
                'sector' => $sector->description,
            ]));
        }
        return $this->goBack();
    }

    public function actionPurchaseCart()
    {
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello();
        $tickets = $query->all();
        foreach ($tickets as $ticket) {
            $ticket->purchase();
        }
        Growl::add(Growl::SUCCESS,
            Yii::t('app', 'Troverà i suoi biglietti nella sua area personale.'),
            Yii::T('app', 'Grazie per l\'acquisto!'),
            'fa fa-check'
        );
        return $this->redirect(['personal-area/tickets']);
    }

    /**
     * @param $id
     * @return Event|null
     * @throws NotFoundHttpException
     */
    public function findModel($id)
    {
        $model = Event::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Sector|null
     * @throws NotFoundHttpException
     */
    public function findSectorModel($id)
    {
        $model = Sector::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Ticket|null
     * @throws NotFoundHttpException
     */
    public function findTicketModel($id)
    {
        $model = Ticket::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }
}

frontend/views/event/cart.php
<?php

use common\models\Event;
use common\models\Ticket;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $tickets Ticket[]
 * @var $totalCount
 */

$this->title = Yii::t('app', 'Carrello');

/**
 * @var $events Event[]
 * @var $ticketEvents Ticket[]
 */
$events = [];
$ticketEvents = [];
foreach ($tickets as $ticket) {
    if (!isset($events[$ticket->sector->idEvent])) {
        $events[$ticket->sector->idEvent] = $ticket->sector->event;
        $ticketEvents[$ticket->sector->idEvent] = [];
    }
    $ticketEvents[$ticket->sector->idEvent][] = $ticket;
}
?>
<h1 class="text-center mt-3 mb-0"><?= $this->title ?></h1>
<div class="container">
    <div class="row">
      <div class="col-lg-6 tickets-cart">
        <?php foreach ($events as $event): ?>
            <div class="card ticket-list shadow bg-light mb-4 p-2">
              <div class="row">
                <div class="col-lg-5">
                  <a href="<?= Url::to(['event/view', 'id' => $event->idEvent]) ?>">
                      <img class="img-fluid rounded" alt="Responsive image" src="<?= $event->getPreviewPath() ?>">
                  </a>
                </div>
                <div class="col-lg-7">
                  <h4 class="mb-3"><b><?= $event->title ?></b></h4>
                  <?= $event->location ?><b class="text-success"><br><?= Yii::$app->formatter->asDatetime($event->dateTime) ?></b>
                </div>
              </div>
                <?php foreach ($ticketEvents[$event->idEvent] as $ticket): ?>
                    <hr>
                    <?php $sector = $ticket->sector; ?>
                    <b>Info biglietto</b>
                    Biglietto numero: <?= $ticket->info ?><br>
                    Settore: <?= $sector->description; ?><br>
                    Prezzo: <?= Yii::$app->formatter->asCurrency($sector->price) ?><br><br>
                    <a class="btn btn-outline-danger"
                       href="<?= Url::to(['event/cart-delete', 'id' => $ticket->idTicket]) ?>"><span
                                class="fa fa-trash"></span> Rimuovi dal carrello</a>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
      </div>
      <div class="col-lg-5 ml-5 summary-cart">
        <h6 class="text-center">RIEPILOGO</h6>
        <hr>
        <?php foreach ($events as $event): ?>
          <?php echo count($ticketEvents[$event->idEvent]) ?> x <b><?= $event->title ?></b>
          <span style="float:right"><?php
          $price = 0;
          foreach ($ticketEvents[$event->idEvent] as $ticket) {
            $sector = $ticket->sector;
            $price += $sector->price;
          }
          echo Yii::$app->formatter->asCurrency($price);
           ?></span><br>
          <?= $event->location ?><b class="text-success"><br><?= Yii::$app->formatter->asDatetime($event->dateTime) ?></b><br>
          <hr>
          <?php endforeach; ?>
          <b>Importo totale:</b><span style="float:right"><?= Yii::$app->formatter->asCurrency($totalCount) ?></span> <br>

        <button class="btn btn-confirm-payment mt-5" style="float:right" onclick="
                $('#pay-modal').modal('show');
                setTimeout(function () {
                location.href='<?= Url::to(['event/purchase-cart']); ?>';
                }, 2000);
                ">Conferma e paga
        </button>
      </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="pay-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="height:200px;">
                <div class="modal-body text-center align-middle">
                    <h3>Pagamento in corso <br><br><i class="fas fa-spinner fa-spin"></i></h3>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/event/search-results.php
<?php

use common\models\Category;
use common\models\Event;
use frontend\models\EventSearch;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $events Event[]
 * @var $query String
 * @var $searchModel EventSearch
 */

$this->title = Yii::t('app', 'Ricerca Evento');
?>


<?php if (count($events) == 0): ?>
    Nessun risultato.
<?php else: ?>
    <div class="row">
        <div class="col-md-2 filter-column">
            Visualizzati <?= count($events) ?> elementi.<br>
            <?php $form = ActiveForm::begin([
                'action' => Url::to(['event/search'])
            ]); ?>
            <?= $form->field($searchModel, 'title') ?>
            <?= $form->field($searchModel, 'location') ?>
            <?= $form->field($searchModel, 'idCategory')->widget(Select2::class, [
                'data' => array_merge([0 => 'Tutte le categorie'], ArrayHelper::map(Category::find()->all(), 'idCategory', 'description'))
            ]) ?>
            <input type="submit" class="btn btn-create-event btn-block">
            <?php $form::end() ?>
        </div>
        <div class="col-md-10 cards-filter">
            <div class="card-deck">
                <?php foreach ($events as $event): ?>
                    <div class="col-md-3 mb-5">
                        <div class="card event-card">
                            <a href="<?= Url::to(['event/view', 'id' => $event->idEvent]) ?>">
                                <img src="<?= $event->getPreviewPath() ?>" class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title text-center"><?= $event->title ?></h5>
                                <p class="card-text"><?= $event->description ?></p>
                            </div>
                            <div class="card-footer">
                                <p><strong><?= Yii::t('app', 'Località') ?>:</strong> <?= $event->location ?><br>
                                    <strong><?= Yii::t('app', 'Data') ?>
                                        :</strong> <?= Yii::$app->formatter->asDatetime($event->dateTime); ?></p>
                                <!-- <small class="text-muted"><?= $event->location ?> | <?= Yii::$app->formatter->asDatetime($event->dateTime); ?></small> -->
                            </div>
                        </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

frontend/views/event/view.php
<?php

use common\models\Event;
use common\models\Sector;
use frontend\models\form\TicketForm;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $event Event
 * @var $sectors Sector[]
 * @var $categoryEvents Event[]
 */

$this->title = Yii::t('app', 'Evento {title}', ['title' => $event->title]);
?>


<div class="row">
    <div id = "div1" style="display:block" class="col-md-5">
        <img class="img-fluid rounded shadow" alt="Responsive image" src="<?= $event->getPreviewPath() ?>">
    </div>
    <div id = "div2" style="display:none" class="col-md-5">
        <div id="map" class="map"></div>
    </div>
    <div class="col-md-7">
        <div class="container" style="margin-top: 2%;">
            <h1><b><div class="text-center"><?= $event->title ?></div></b></h1><br>
            <div class="text-justify"><?= $event->description ?></div>
            <br><br>
            <div class="row">
                <div class="col-md-6">
                    <div class="text-center">L' evento si terrà a <h2><b><?= $event->location ?></b></h2> in data <h2>
                            <b><?= Yii::$app->formatter->asDatetime($event->dateTime) ?></b></h2><br></div>
                </div>
                <div class="col-md-6">
                    <button id="button-map" class="btn btn-create-sector btn-lg btn-block"
                            onclick="replace();return false">Visualizza la mappa
                    </button>
                </div>
            </div>
            <?php
            $sell = empty($event->dateTimeSellStart) ||
                empty($event->dateTimeSellEnd) ||
                (date('U') > $event->dateTimeSellStart && date('U') < $event->dateTimeSellEnd);
            if ($sell): ?>
                <div class="alert alert-success alert-event" role="alert">
                    <div class="text-center">acquista ora i tuoi biglietti selezionando il settore qui sotto!</div>
                </div>
            <?php else: ?>
                <div class="alert alert-danger alert-event" role="alert">
                    <div class="text-center">La vendita dei biglietti per questo evento inizierà in
                        data <?= Yii::$app->formatter->asDatetime($event->dateTimeSellStart) ?> e finirà in data <?= Yii::$app->formatter->asDatetime($event->dateTimeSellEnd) ?></div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="container-events">
    <table class="table table-striped table-responsive-sm">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Settore</th>
            <th scope="col">Biglietti Rimanenti</th>
            <th scope="col">Prezzo</th>
            <th scope="col">Acquista</th>
        </tr>
        </thead>
        btn-
        <tbody>
        <?php foreach ($sectors as $sector): ?>
            <tr>
                <th scope="row"><span class="badge" style="background-color:<?= $sector->color ?>">&nbsp;</span><br>
                </th>
                <td><?= $sector->description ?></td>
                <td><?= $sector->remainingTickets ?></td>
                <td><?= Yii::$app->formatter->asCurrency($sector->price); ?></td>
                <td>
                    <?php if (!$sell): ?>
                            Non acquistabile
                    <?php else: ?>
                        <?php if (isset(Yii::$app->user->identity) && !Yii::$app->user->identity->isManager()): ?>
                            <?php
                            $model = new TicketForm();
                            $model->idSector = $sector->idSector;

                            $form = ActiveForm::begin([
                                'action' => Url::to(['event/add-to-cart']),
                                'enableAjaxValidation' => true,
                                'options' => ['class' => 'm-0']
                            ]); ?>
                            <?= $form->field($model, 'idSector', ['options' => ['class' => 'm-0']])->hiddenInput(['class' => 'm-0'])->label(false); ?>
                            <div class="row">
                                <div class="col">
                                    <?= $form->field($model, 'quantity', ['options' => ['class' => 'm-0']])->textInput(['placeholder' => 'Quantità'])->label(false) ?>
                                </div>
                                <div class="col">
                                    <input type="submit" class="btn btn-create-sector btn-sm btn-block"
                                           value="Aggiungi al Carrello">
                                </div>
                            </div>
                            <?php $form::end(); ?>
                        <?php else: ?>
                            Gli account manager non possono acquistare biglietti.
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if (count($categoryEvents) > 0 && isset($event->category)): ?>
        <hr class="my-5">
        <h2 class="text-center">Altri eventi della categoria <?= $event->category->description ?></h2>
        <div class="card-deck">
            <?php foreach ($categoryEvents as $event): ?>
                <div class="col-md-3 mb-5">
                    <div class="card event-card">
                        <a href="<?= Url::to(['event/view', 'id' => $event->idEvent]) ?>">
                            <img src="<?= $event->getPreviewPath() ?>" class="card-img-top" alt="...">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title text-center"><?= $event->title ?></h5>
                            <p class="card-text"><?= $event->description ?></p>
                        </div>
                        <div class="card-footer">
                            <p><strong><?= Yii::t('app', 'Località') ?>:</strong> <?= $event->location ?><br>
                                <strong><?= Yii::t('app', 'Data') ?>
                                    :</strong> <?= Yii::$app->formatter->asDatetime($event->dateTime); ?></p>
                            <!-- <small class="text-muted"><?= $event->location ?> | <?= Yii::$app->formatter->asDatetime($event->dateTime); ?></small> -->
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<script>
    // Initialize and add the map
    function initMap() {
        // The location of Uluru
        var uluru = {
            lat: <?php if (!empty($event->latitude)) {
                echo $event->latitude;
            }?>, lng: <?php if (!empty($event->longitude)) {
                echo $event->longitude;
            }?>};
        // The map, centered at Uluru
        var map = new google.maps.Map(
            document.getElementById('map'), {zoom: 12, center: uluru});
        // The marker, positioned at Uluru
        var marker = new google.maps.Marker({position: uluru, map: map});
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSYB-eyKge2IJBYYXnQwW7tGhud1rBuvU&callback=initMap">
</script>
<script>
    function replace() {
        if(document.getElementById("div1").style.display ==="none") {
            document.getElementById("button-map").textContent ="Visualizza la mappa";
            document.getElementById("div1").style.display="block";
            document.getElementById("div2").style.display="none";
        } else {
            document.getElementById("button-map").textContent ="nascondi la mappa";
            document.getElementById("div1").style.display="none";
            document.getElementById("div2").style.display="block";
        }
    }
</script>