frontend/controllers/EventController.php
<?php

namespace frontend\controllers;

use common\models\Event;
use common\models\Sector;
use common\models\Ticket;
use frontend\models\EventSearch;
use frontend\models\form\TicketForm;
use frontend\widgets\Growl;
use Yii;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Event controller
 */
class EventController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionSearch($q = null)
    {
        if (!isset($q)) {
            $q = Yii::$app->request->post('q');
        }
        if (isset($q)) {
            $query = Event::find()->andWhere(['or',
                ['like', 'description', $q],
                ['like', 'title', $q],
                ['like', 'location', $q],
            ])->limit(200);
            $searchModel = new EventSearch();
            $searchModel->title = $q;
        } else {
            $searchModel = new EventSearch();
            if ($searchModel->load(Yii::$app->request->post())) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($searchModel);
                } else {
                    $query = $searchModel->generateQuery(Yii::$app->request->post());
                }
            } else {
                throw new BadRequestHttpException();
            }
        }
        $events = $query->all();
        return $this->render('search-results', [
            'query' => $q,
            'events' => $events,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        Url::remember();
        $model = $this->findModel($id);
        $sectors = $model->sectors;

        $categoryEvents = Event::find()->category($model->idCategory)->andWhere(['!=', 'Event.idEvent', $model->idEvent])->limit(4)->all();
        return $this->render('view', ['event' => $model, 'sectors' => $sectors, 'categoryEvents' => $categoryEvents]);
    }

    public function actionAddToCart()
    {
        $model = new TicketForm();
        if ($model->load($_POST)) {
            $sector = $this->findSectorModel($model->idSector);
            $event = $sector->event;
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->create()) {
                Growl::add(Growl::SUCCESS,
                    Yii::t('app', 'Sono stati aggiunti al carrello <b>{quantity}</b> biglietti per il settore <b>{sector}</b> dell\'evento <b>{event}</b>', [
                        'quantity' => $model->quantity,
                        'sector' => $sector->description,
                        'event' => $event->title,
                    ]),
                    Yii::t('app', 'Biglietto/i aggiunti al carrello.'),
                    'fa fa-cart-plus'
                );
                return $this->goBack();
            }
        }
        throw new BadRequestHttpException();
    }

    public function actionCart()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello()->orderBy('Event.idEvent, Sector.idSector');
        $tickets = $query->all();
        if (count($tickets) == 0) {
            return $this->redirect(['site/index']);
        }
        $total = $query->sum('Sector.price');
        return $this->render('cart', ['tickets' => $tickets, 'totalCount' => $total]);
    }

    public function actionCartDelete($id)
    {
        $ticket = $this->findTicketModel($id);
        $sector = $ticket->sector;
        $event = $sector->event;
        if ($ticket->idUser != Yii::$app->user->getId()) throw new ForbiddenHttpException();
        if ($ticket->delete()) {
            Growl::add(Growl::WARNING, Yii::t('app', 'Biglietto <b>{ticket}</b> per <b>{event}</b> - <b>{sector}</b> rimosso dal carrello', [
                'ticket' => $ticket->info,
                'event' => $event->title,
                'sector' => $sector->description,
            ]));
        }
        return $this->goBack();
    }

    public function actionPurchaseCart()
    {
        $user = Yii::$app->user->identity;
        $query = $user->getTickets()->joinWith(['sector', 'sector.event'])->carrello();
        $tickets = $query->all();
        foreach ($tickets as $ticket) {
            $ticket->purchase();
        }
        Growl::add(Growl::SUCCESS,
            Yii::t('app', 'Troverà i suoi biglietti nella sua area personale.'),
            Yii::T('app', 'Grazie per l\'acquisto!'),
            'fa fa-check'
        );
        return $this->redirect(['personal-area/tickets']);
    }

    /**
     * @param $id
     * @return Event|null
     * @throws NotFoundHttpException
     */
    public function findModel($id)
    {
        $model = Event::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Sector|null
     * @throws NotFoundHttpException
     */
    public function findSectorModel($id)
    {
        $model = Sector::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Ticket|null
     * @throws NotFoundHttpException
     */
    public function findTicketModel($id)
    {
        $model = Ticket::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }
}

frontend/controllers/PersonalAreaController.php
<?php

namespace frontend\controllers;

use common\models\Event;
use common\models\Sector;
use common\models\Ticket;
use frontend\models\form\EventForm;
use frontend\widgets\Growl;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Personal Area Controller
 */
class PersonalAreaController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionDetail()
    {
        Url::remember();
        $model = Yii::$app->user->identity;
        return $this->renderView($model, 'detail', ['model' => $model]);
    }

    public function renderView($model, $view, $params = [])
    {
        return $this->render('view', ['model' => $model,
            'content' => $this->renderPartial($view, $params)
        ]);
    }

    public function actionEventCreate()
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $model = new EventForm();
        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->create()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento creato correttamente'));
                return $this->redirect(['personal-area/event-detail', 'id' => $model->idEvent]);
            }
        }
        return $this->renderView($user, 'event-create', ['model' => $model]);
    }

    public function actionDashboard()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $query = Event::find()->orderBy('Event.dateTime');
        if (!$user->isAdmin()) {
            $query->createdBy($user->id);
        }
        $events = $query->all();
        $idEvents = array_values(ArrayHelper::map($events, 'idEvent', 'idEvent'));
        $countSoldTickets = Ticket::find()->joinWith('sector')
            ->sold()->andWhere(['Sector.idEvent' => $idEvents])->count();
        $totalSoldTickets = Ticket::find()->joinWith('sector')
            ->sold()->andWhere(['Sector.idEvent' => $idEvents])->sum('Sector.price');
        $countUnsoldTickets = Sector::find()->andWhere(['Sector.idEvent' => $idEvents])->sum('maxTickets') - $countSoldTickets;
        return $this->renderView($user, 'dashboard', [
            'events' => $events,
            'countSoldTickets' => $countSoldTickets,
            'totalSoldTickets' => $totalSoldTickets,
            'countUnsoldTickets' => $countUnsoldTickets,
        ]);
    }

    public function actionEvents()
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $query = Event::find()->orderBy('Event.dateTime');
        if (!$user->isAdmin()) {
            $query->createdBy($user->id);
        }
        $events = $query->all();

        return $this->renderView($user, 'events', ['events' => $events]);
    }

    public function actionEventDetail($id)
    {
        Url::remember();
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        $sectors = $model->sectors;
        return $this->renderView($user, 'event-detail', [
            'model' => $model,
            'sectors' => $sectors,
        ]);
    }

    public function actionEventDelete($id)
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        if ($model->delete()) {
            Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento eliminato correttamente'));
        }
        return $this->redirect(['personal-area/events']);
    }

    public function actionEventUpdate($id)
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        $model = $this->findEventModel($id);
        if (!$user->isAdmin() && $model->idUser != $user->getId()) throw new ForbiddenHttpException();

        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->save()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Evento modificato correttamente'));
                return $this->goBack();
            }
        }
        return $this->renderView($user, 'event-update', ['model' => $model]);
    }

    public function actionSectorCreate()
    {
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();

        $model = new Sector();
        if ($model->load($_POST)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->save()) {
                Growl::add(Growl::SUCCESS, Yii::t('app', 'Settore creato correttamente'));
                return $this->goBack();
            }
        }
        return $this->renderView($user, 'event-create', ['model' => $model]);
    }

    public function actionSectorDelete($id)
    {
        $sector = $this->findSectorModel($id);
        $event = $sector->event;
        $user = Yii::$app->user->identity;
        if (!$user->isManager()) throw new ForbiddenHttpException();
        if (!$user->isAdmin() && $event->idUser != $user->getId()) throw new ForbiddenHttpException();
        if ($sector->delete()) {
            Growl::add(Growl::SUCCESS, Yii::t('app', 'Settore eliminato correttamente'));
        }
        return $this->goBack();
    }

    public function actionTickets()
    {
        $user = Yii::$app->user->identity;
        $tickets = $user->getTickets()
            ->sold()
            ->joinWith(['sector', 'sector.event'])
            ->orderBy('Event.dateTime desc')
            ->all();
        return $this->render('tickets', ['tickets' => $tickets]);

    }

    /**
     * @param $id
     * @return Event|null
     * @throws NotFoundHttpException
     */
    public function findEventModel($id)
    {
        $model = Event::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }

    /**
     * @param $id
     * @return Sector|null
     * @throws NotFoundHttpException
     */
    public function findSectorModel($id)
    {
        $model = Sector::findOne($id);
        if (!isset($model))
            throw new NotFoundHttpException();
        return $model;
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this View */
/* @var $content string */

use common\models\LoginForm;
use common\widgets\Alert;
use frontend\assets\AppAsset;
use frontend\models\form\SignupForm;
use frontend\widgets\Growl;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" type="image/jpg" href="<?= Yii::getAlias("@web") . "/img/favicon.jpg" ?>"/>
    <?php $this->head() ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<?php $this->beginBody() ?>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top ">
    <a class="navbar-brand" href="<?= Url::to(['site/index']) ?>">
        <img src="<?= Yii::getAlias('@web/img/logo.png') ?>" class="d-inline-block align-top" alt="logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="search-content form-inline col-lg-9 justify-content-center" action="<?= Url::to(['event/search']) ?>">
            <!-- <input class="form-control searchicon" type="image" src="../img/searchicon.png"> -->
            <input class="form-control searchbar w-75" type="search" placeholder="" autocomplete="off"
                   autofocus="autofocus" name="q">
            <button class="btn btn-filter" type="submit">Cerca</button>
        </form>
        <ul class="navbar-nav ml-auto">
            <?php if (Yii::$app->user->isGuest): ?>
                <li class="nav-item">
                    <button type="button" class="btn btn-navbar" data-toggle="modal"
                            data-target="#modal-login">Log In
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-navbar" data-toggle="modal"
                            data-target="#modal-register">Registrati
                    </button>
                </li>
            <?php else: ?>
                <!-- <li class="nav-item">
                  <a class="btn btn-outline-success"><span class="fa fa-user">Carrello</a>
                </li> -->
                <?php if (Yii::$app->user->identity->isManager()): ?>
                    <li class="nav-item">
                        <a href="<?= Url::to(['personal-area/dashboard']) ?>" class="btn btn-navbar"><span
                                class="fas fa-user-shield"> Area Personale</a>
                    </li>
                <?php else: ?>
                    <?php
                    $cartCount = Yii::$app->user->identity->getTickets()->carrello()->count();
                    ?>
                    <li class="nav-item">
                        <a href="<?= Url::to(['event/cart']) ?>"
                           class="btn btn-navbar <?= $cartCount == 0 ? 'disabled' : '' ?>">
                            <i class="fa fa-cart-plus"></i>
                            <span class="d-md-none"> Carrello</span>
                            <span class="badge badge-info"><?= $cartCount ?></span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="btn btn-navbar" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Account
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<?= Url::to(['personal-area/tickets']) ?>"><i
                                        class="fas fa-ticket-alt"></i> I miei biglietti</a>
                            <a class="dropdown-item" href="<?= Url::to(['personal-area/detail']) ?>"><i
                                        class="fas fa-cog"></i> Opzioni</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?= Url::to(['site/logout']) ?>"><i
                                        class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        </ul>
    </div>
</nav>
<div class="wrap d-flex min-vh-100 flex-column">
    <?= Alert::widget() ?>
    <?= Growl::widget() ?>
    <?= $content ?>
</div>

<!-- Log In Modal -->
<div id="modal-login" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="row no-gutters">
                <div class="insertion col-lg-6">
                    <button type="button" class="close close-log" data-dismiss="modal" aria-label="Close">
                        <img class="img-fluid" src="<?= Yii::getAlias('@web/img/close.png') ?>">
                    </button>
                    <div class="container text-center">
                        <h2>LOG IN</h2>
                        <span class="info"><p>Bentornato! Accedi al tuo account.</p></span>
                        <?php
                        $signinModel = new LoginForm();
                        $form = ActiveForm::begin([
                            'action' => Url::to(['site/login']),
                            'enableAjaxValidation' => true,
                            'enableClientValidation' => false
                        ]);
                        ?>
                        <div class="form-group fg">
                            <?= $form->field($signinModel, 'email')->textInput([
                                'class' => 'form-control',
                                'placeholder' => $signinModel->getAttributeLabel('email')
                            ])->label(false); ?>
                        </div>
                        <div class="form-group fg">
                            <?= $form->field($signinModel, 'password')->passwordInput([
                                'class' => 'form-control',
                                'placeholder' => $signinModel->getAttributeLabel('password')
                            ])->label(false); ?>
                        </div>
                        <div class="justify-content-around">
                            <div>
                                <!-- Remember me -->
                                <div class="custom-control custom-checkbox">
                                    <?= $form->field($signinModel, 'rememberMe')->checkbox() ?>
                                </div>
                            </div>
                            <div>
                                <!-- Forgot password -->
                                <!--a href="">Forgot password?</a-->
                            </div>
                        </div>
                        <?= Html::submitButton(Yii::t('app', 'Accedi'), ['class' => 'btn btn-dark btn-important']) ?>
                        <?= Html::button(Yii::t('app', 'Registrati'), [
                            'class' => 'btn btn-light',
                            'data-dismiss' => 'modal',
                            'data-toggle' => 'modal',
                            'data-target' => '#modal-register'
                        ]) ?>
                        <footer>
                            <a href="#">Term of use. Privacy Policy</a>
                        </footer>
                        <?php $form::end(); ?>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img class="img-fluid" src="<?= Yii::getAlias('@web/img/loginReg.jpg') ?>">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Register Modal -->
<div id="modal-register" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="row no-gutters">
                <div class="col-lg-6">
                    <img class="img-fluid" src="<?= Yii::getAlias('@web/img/loginReg.jpg') ?>">
                </div>
                <div class="insertion col-lg-6">
                    <button type="button" class="close close-reg" data-dismiss="modal" aria-label="Close">
                        <img class="img-fluid" src="<?= Yii::getAlias('@web/img/close.png') ?>">
                    </button>
                    <div class="container text-center">
                        <h2><?= Yii::t('app', 'REGISTRATI') ?></h2>
                        <span class="info"><p>Completa i seguenti campi per creare il tuo account.</p></span>
                        <?php
                        $signupModel = new SignupForm();
                        $form = ActiveForm::begin([
                            'action' => Url::to(['site/signup']),
                            'enableAjaxValidation' => true,
                            'enableClientValidation' => false
                        ]);
                        ?>
                        <div class="row form-group fg">
                            <div class="col">
                                <?= $form->field($signupModel, 'firstname')->textInput([
                                    'id' => 'fname',
                                    'class' => 'form-control',
                                    'placeholder' => $signupModel->getAttributeLabel('firstname')
                                ])->label(false); ?>
                            </div>
                            <div class="col">
                                <?= $form->field($signupModel, 'lastname')->textInput([
                                    'id' => 'lname',
                                    'class' => 'form-control',
                                    'placeholder' => $signupModel->getAttributeLabel('lastname')
                                ])->label(false); ?>
                            </div>
                        </div>
                        <div class="form-group fg">
                            <?= $form->field($signupModel, 'email')->textInput([
                                'class' => 'form-control',
                                'placeholder' => $signupModel->getAttributeLabel('email')
                            ])->label(false); ?>
                        </div>
                        <div class="form-group fg">
                            <?= $form->field($signupModel, 'password')->passwordInput([
                                'class' => 'form-control',
                                'placeholder' => $signupModel->getAttributeLabel('password')
                            ])->label(false); ?>
                        </div>
                        <div class="form-group fg">
                            <?= $form->field($signupModel, 'password_confirm')->passwordInput([
                                'class' => 'form-control',
                                'placeholder' => $signupModel->getAttributeLabel('password_confirm')
                            ])->label(false); ?>
                        </div>
                        <div class="justify-content-around">
                            <div class="fg ckc">
                                <div class="custom-control custom-checkbox">
                                    <?= $form->field($signupModel, 'isManager')->checkbox(); ?>
                                </div>
                            </div>
                        </div>
                        <?= Html::button(Yii::t('app', 'Accedi'), [
                            'class' => 'btn btn-light',
                            'data-dismiss' => 'modal',
                            'data-toggle' => 'modal',
                            'data-target' => '#modal-login'
                        ]) ?>
                        <?= Html::submitButton(Yii::t('app', 'Registrati'), ['class' => 'btn btn-dark btn-important']) ?>
                        <footer>
                            <a href="#">Term of use. Privacy Policy</a>
                        </footer>
                        <?php $form::end() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="footer text-white">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>
    </div>
</footer>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>